### ISSUE TITLE
Rédiger un README pour expliquer à quoi correspond ce projet

### ISSUE THREAD

**Issue by pascalfares** [Ritakhalil/1508n_ritakhalil_c1_2021_angular#1]

**Comment by Ritakhalil** [comment]
Le projet consiste a ajouter une recette avec un nom, une image a partir du web (URL), une description et des ingredients et leurs quatités. On peut modifer ou supprimer une recette.
De plus dans la partie "shopping list", on peut ajouter des éléments avec une quantité pour chacune. 
On peut ajouter les ingrédients d'une recette dans la "shopping list" en cliquant "To Shopping List".
